name: deploy-application

on:
  push:
    branches:
      - main
jobs:
  create-deployment-artifacts:
    name: Create deploy artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Compile CSS and Javascript
        run:
          npm install
          npm run


